apiVersion: v1
kind: Namespace
metadata:
  name: demo-dev-<no value>-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:27dae2dbb04f70f09a8fa39aea8d4efb65c60753