apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    dreamkast.cloudnativedays.jp/app-commit-hash: b712aee24d10c28af0cb2ba464d2c45f117bdd71
    dreamkast.cloudnativedays.jp/app-organization: ShotaKitazawa
    dreamkast.cloudnativedays.jp/app-repository: reviewapp-operator-demo-app
  creationTimestamp: null
  name: sample-1
  namespace: argocd
spec:
  destination:
    namespace: sample-1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ovarlays/dev/sample-1
    repoURL: https://github.com/ShotaKitazawa/reviewapp-operator-demo-infra
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
