apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    dreamkast.cloudnativedays.jp/app-commit-hash: ""
    dreamkast.cloudnativedays.jp/app-organization: ShotaKitazawa
    dreamkast.cloudnativedays.jp/app-repository: reviewapp-operator-demo-app
  name: test-ra-0
  namespace: argocd
spec:
  destination:
    namespace: test-ra-0
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/dev/test-ra-0
    repoURL: https://github.com/ShotaKitazawa/reviewapp-operator-demo-infra
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
