---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: demo
spec:
  rules:
    - host: reviewapp-operator-prd.kanatakita.com
      http:
        paths:
          - backend:
              serviceName: demo
              servicePort: 8080
